version: '3.4'

services:
  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql:8.0
    ports:
      - '3306:3306'
      - '33060:33060'
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: 'America/Sao_Paulo'
    networks:
      - subnet_0
    restart: on-failure
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  user-api:
    container_name: user-api
    hostname: user-api
    image: juliocesarmidia/user-api:latest
    build:
      context: ./api
    command: 'sh -c "yarn install && yarn run dev"'
    restart: on-failure
    networks:
      - subnet_0
    ports:
      - 5050:5050
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASS: ${MYSQL_PASS}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      APP_JWT_SECRET: ${APP_JWT_SECRET}
    volumes:
      - ./api:/app:rw
      - user-api-node-modules:/app/node_modules:rw

networks:
  subnet_0:
    driver: bridge

volumes:
  mysql-data: {}
  user-api-node-modules: {}
  user-ui-node-modules: {}

secrets: {}
